language: php
php:
  - 5.4
env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.6.*"
before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist
script:
  - php ./vendor/phpunit/phpunit/phpunit -c app/ --coverage-clover=build/logs/clover.xml
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/satooshi/php-coveralls/composer/bin/coveralls -v
matrix:
  include:
    # Build with PHP 5.5 and Symfony LTS
    - php: 5.5
      env: SYMFONY_VERSION="2.3.*"
    # Build with latest PHP and Symfony Stable
    - php: 5.6
      env: SYMFONY_VERSION="2.6.*@dev"

  # Test the latest PHP and Symfony Next
  allow_failures:
    - env: SYMFONY_VERSION="2.6.*@dev"

  fast_finish: true

notifications:
  email:
    - dev@dankempster.co.uk

branches:
  only:
    - develop
    - master
