imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        path:     "%database_path%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            axstrad_content: # Required by AxstradPageBundle
                type: yml
                prefix: Axstrad\Component\Content\Orm
                dir: "%kernel.root_dir%/../vendor/axstrad/content/config/Orm"
                alias: AxstradContent
                is_bundle: false
            CmfSeoBundle: # Required by AxstradSeoBundle
                type: xml
                prefix: Symfony\Cmf\Bundle\SeoBundle\Model
                dir: Resources/config/doctrine-model
        filters:
            activatable: # Required by AxstradPageBundle
                class: Axstrad\DoctrineExtensions\Activatable\Filter\OrmFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

## AxstradDoctrineExtensionsBundle
axstrad_doctrine_extensions:
    orm:
        default:
            activatable: true # Required by AxstradPageBundle

## StofDoctrineExtensionsBundle
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable: true # Required by AxstradPageBundle

## Symfony SEO Bundle : extends Sonata SEO Bundle
# required by AxstradSeoBundle
cmf_seo:
    content_key: document
    persistence:
        orm: true
    # Standard page title
    title: "%%content_title%% | %project_name%"

## Sonata SEO Bundle
# required by SymfonySEOBundle
sonata_seo:
    page:
        title: %project_name%
        metas:
            name:
                robots: "index, follow"
            http-equiv:
                'Content-Type': "text/html; charset=utf-8"
                'X-Ua-Compatible': "IE=Edge"
        head:
            'xmlns': "http://www.w3.org/1999/xhtml"
