imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: true

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%kernel.root_dir%/data/test.db3"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

## LiipFunctionalTestBundle
liip_functional_test:
    cache_sqlite_db: true
    query_count.max_query_count: 50
